name: release

on:
  push:
    branches:
      - improve-process

# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: "Version of the new Smash Remix release e.g '1.5.2'."
#         required: true
#         type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: cd release && ./generate.sh "1.5.2"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/smashremix1.5.2.zip"
          bodyFile: release/body.md
          name: "Smash Remix 1.5.2"
          tag: 1.5.2
