name: release

on:
  push:
    branches:
      - improve-process

# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: "Version of the new Smash Remix release e.g '1.5.2'."
#         required: true
#         type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        run: |
          cd release
          ./generate.sh "1.5.2"
