name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the new Smash Remix release e.g '1.5.2'."
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release
        run: cd release && ./generate.sh "${{ inputs.version }}"
